Repository masrufjaman/gas-n-go, pull requests merged in 2021-04, with the labels that each got.

#12 Design to Feature
  eStore/static/eStore/images/audi logo.png
  eStore/static/eStore/images/bmw logo.png
  eStore/static/eStore/images/car 2.png
  eStore/static/eStore/images/car battery.jpeg
  eStore/static/eStore/images/car glass cleaner.jpg
  eStore/static/eStore/images/car headlight.jpg
  eStore/static/eStore/images/car part.png
  eStore/static/eStore/images/car steering wheel.jpg
  eStore/static/eStore/images/car tire.jpg
  eStore/static/eStore/images/car.jpg
  eStore/static/eStore/images/download.jpg
  eStore/static/eStore/images/favicon.ico
  eStore/static/eStore/images/filling station.jpg
  eStore/static/eStore/images/honda logo (2).png
  eStore/static/eStore/images/honda logo.png
  eStore/static/eStore/images/images.jpg
  eStore/static/eStore/images/marcedes benz logo.png
  eStore/static/eStore/images/mini logo.png
  eStore/static/eStore/images/mobil logo.png
  eStore/static/eStore/images/mobil-super-moto-20w-40-4t-fs-square-md.jpg
  eStore/static/eStore/images/moto cycle tire.jpg
  eStore/static/eStore/images/moto gas tank.jpg
  eStore/static/eStore/images/motor 2.png
  eStore/static/eStore/images/motor cycle headlight.jpg
  eStore/static/eStore/images/motor.png
  eStore/static/eStore/images/motorcycle engine.jpg
  eStore/static/eStore/images/nissan logo (2).png
  eStore/static/eStore/images/nissan logo.png
  eStore/static/eStore/images/parts.png
  eStore/static/eStore/images/parts2.png
  eStore/static/eStore/images/petrol pump.jpg.crdownload
  eStore/static/eStore/images/pic.6.jpg (1).png
  eStore/static/eStore/images/pic.6.jpg (3).png
  eStore/static/eStore/images/profile.png
  eStore/static/eStore/images/toppng.com-nissan-logo-vector-512x512.png
  eStore/static/eStore/images/toppng.com-peugeot-logo-2000x1409.png
  eStore/static/eStore/images/toppng.com-volvo-car-logo-2278x1909.png
  eStore/static/eStore/images/toyota logo.png
  eStore/static/eStore/images/truck battery.jpg
  eStore/static/eStore/images/truck rubber bushing.jpg
  eStore/static/eStore/images/wind sheild glass.jpg.crdownload
  eStore/static/eStore/images/windsheild.jpg
  eStore/static/eStore/js/index.js
  eStore/static/eStore/styles/index.css
  eStore/static/eStore/styles/index.css.map
  eStore/static/eStore/styles/index.scss
  eStore/templates/eStore/index.html
  eStore/views.py
Labels: design

#13 About Us & Contact US
  home/contact us page/image/Picture.jpg
  home/contact us page/image/contact.jpg
  home/contact us page/image/kirill-sharkovski-QRB7o5XJm60-unsplash.jpg
  home/contact us page/image/pexels-pixabay-531880.jpg
  home/contact us page/image/zoe-BVoTTLwXvMQ-unsplash.jpg
  home/contact us page/index.html
  home/contact us page/style.css
  home/static/home/images/pic.jpg
  home/static/home/styles/about.css
  home/static/home/styles/about.css.map
  home/static/home/styles/about.scss
  home/static/home/styles/contact.css
  home/static/home/styles/contact.css.map
  home/static/home/styles/contact.scss
  home/templates/home/about.html
  home/templates/home/base.html
  home/templates/home/contact.html
  home/urls.py
  home/views.py
Labels: design

#14 Home page(About Us, Contact Us)
  home/static/home/images/Picture.jpg
  home/static/home/images/pic.jpg
  home/static/home/styles/about.css
  home/static/home/styles/about.css.map
  home/static/home/styles/about.scss
  home/static/home/styles/contact.css
  home/static/home/styles/contact.css.map
  home/static/home/styles/contact.scss
  home/templates/home/about.html
  home/templates/home/base.html
  home/templates/home/contact.html
  home/templates/home/help.html
  home/urls.py
  home/views.py
Labels: design

#15 Payment Page
  home/static/home/styles/payment.css
  home/static/home/styles/payment.css.map
  home/static/home/styles/payment.scss
  home/templates/home/base.html
  home/templates/home/payment.html
  home/urls.py
  home/views.py
Labels: enhancement

#19 Completed the change of the text
  home/templates/home/about.html
  home/templates/home/base.html
  home/templates/home/home.html
Labels: fix

#20 Created Cart Page
  eStore/static/eStore/styles/cart.css
  eStore/static/eStore/styles/cart.css.map
  eStore/static/eStore/styles/cart.scss
  eStore/templates/eStore/cart.html
  eStore/templates/eStore/item_list.html
  eStore/urls.py
  eStore/views.py
  home/templates/home/base.html
Labels: design

#21 Added Membership Card
  home/static/home/images/CHIPS.png
  home/static/home/styles/membership.css
  home/static/home/styles/membership.css.map
  home/static/home/styles/membership.scss
  home/templates/home/base.html
  home/templates/home/membership.html
  home/urls.py
  home/views.py
Labels: design
